Align minimum rust version to 1.86 (#47)
* Align minimum rust version to 1.86

An issue was mentioned in https://github.com/heroku/buildpacks-deb-packages/issues/110#issuecomment-2997899858. This code was added in https://github.com/heroku-buildpacks/bullet_stream/pull/43/files and uses a feature of Rust 1.86 https://www.reddit.com/r/rust/comments/1ip51qt/trait_upcasting_stabilized_in_186/ (https://github.com/rust-lang/rust/pull/134367). 

This usage wasn't realized at the time. No lints or tooling caught it. That Any upcast is critical for the feature introduced in #43. The easiest path forward is to align the MSRV with the reality of the current code.


Semver version bump guidance from this thread to make this a minor change:
https://users.rust-lang.org/t/rust-version-requirement-change-as-semver-breaking-or-not/20980/2.

* Fix clippy lint

```
error: variables can be used directly in the `format!` string
   --> src/global.rs:678:9
    |
678 |         assert!(result.is_err(), "Expected panic to be caught {:?}", result);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
    = note: `-D clippy::uninlined-format-args` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::uninlined_format_args)]`
help: change this to
    |
678 -         assert!(result.is_err(), "Expected panic to be caught {:?}", result);
678 +         assert!(result.is_err(), "Expected panic to be caught {result:?}");
    |

error: could not compile `bullet_stream` (lib test) due to 1 previous error
```